# Generated by Django 4.0.1 on 2022-01-19 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productgroup_options_alter_producttype_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgroup',
            options={},
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={},
        ),
    ]
