# Generated by Django 4.0.1 on 2022-01-30 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brand',
            new_name='product_brand',
        ),
    ]
