# Generated by Django 4.0.1 on 2022-02-17 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
        ('products', '0012_product_has_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_brand',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brands.brand'),
        ),
        migrations.DeleteModel(
            name='ProductBrand',
        ),
    ]
