# Generated by Django 4.0.1 on 2022-02-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_review_options_rename_date_review_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text_review',
            field=models.TextField(blank=True, max_length='1024', null=True),
        ),
    ]
